https://онлайн-читать.рф – request error: Failed to parse: https://онлайн-читать.рф
https://beru.ru%20tiu.ru – request error: HTTPSConnectionPool(host='beru.ru%20tiu.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1054d95d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://irr.ru – request error: HTTPSConnectionPool(host='irr.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1046d9650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://rulit.online – request error: HTTPSConnectionPool(host='rulit.online', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10251ecd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://futurerussia.gov.ru – request error: HTTPSConnectionPool(host='futurerussia.gov.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1052f73d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://aliexpress.ru – request error: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect data check'))
https://kodeks.rusudact.ru – request error: HTTPSConnectionPool(host='kodeks.rusudact.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c4e050>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://онлайнинспекция.рф – request error: Failed to parse: https://онлайнинспекция.рф
https://money.yandex.ru – request error: HTTPSConnectionPool(host='money.yandex.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104d1edd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
